# Generated by Django 4.2 on 2026-04-13 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpDesk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(blank=True, max_length=20, unique=True)),
                ('solicitante_id', models.IntegerField(blank=True, null=True)),
                ('responsable_id', models.IntegerField(blank=True, null=True)),
                ('origen', models.CharField(choices=[('error', 'Error'), ('solicitud', 'Solicitud'), ('consulta', 'Consulta'), ('mantenimiento', 'Mantenimiento')], max_length=20)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], max_length=10)),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('en_progreso', 'En progreso'), ('en_espera', 'En espera'), ('resuelto', 'Resuelto'), ('cerrado', 'Cerrado')], default='abierto', max_length=15)),
                ('descripcion_problema', models.TextField()),
                ('descripcion_solucion', models.TextField(blank=True, null=True)),
                ('fecha_asignacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_compromiso', models.DateTimeField(blank=True, null=True)),
                ('fecha_efectividad', models.DateTimeField(blank=True, null=True)),
                ('tiempo_estimado', models.PositiveIntegerField(help_text='Horas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='helpdesks', to='catalog.service')),
            ],
            options={
                'db_table': 'helpdesks_helpdesk',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HDComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor_id', models.IntegerField(blank=True, null=True)),
                ('contenido', models.TextField()),
                ('es_interno', models.BooleanField(default=False, help_text='Solo visible para TI')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('help_desk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='helpdesks.helpdesk')),
            ],
            options={
                'db_table': 'helpdesks_hdcomment',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='HDAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('archivo', 'Archivo'), ('url', 'URL')], max_length=10)),
                ('nombre', models.CharField(max_length=200)),
                ('valor', models.TextField(help_text='Ruta del archivo o URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('help_desk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='helpdesks.helpdesk')),
            ],
            options={
                'db_table': 'helpdesks_hdattachment',
                'ordering': ['-created_at'],
            },
        ),
    ]
